In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
import numpy as np

In [2]:
from tensorflow.keras.utils import to_categorical

## read the data


In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

## Train the model

In [8]:
x_train=x_train/ 255.0
x_test=x_test/255.0

In [9]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [12]:
to_categorical(y_train)

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(60000, 10))

In [13]:
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [14]:
model=Sequential([
    tf.keras.layers.Input(shape=x_train[0].shape),
    Flatten(),
    Dense(128,activation="relu"),
    Dense(10,activation="softmax")
    ])

In [15]:
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.fit(x_train,y_train,epochs=2,validation_split=0.2)

Epoch 1/2
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9204 - loss: 0.2835 - val_accuracy: 0.9561 - val_loss: 0.1516
Epoch 2/2
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9620 - loss: 0.1293 - val_accuracy: 0.9662 - val_loss: 0.1157


# save the model

In [18]:
model.save("keras_model.keras")

In [ ]:
# loading the model

In [19]:
keras_model=load_model("keras_model.keras")

In [20]:
keras_model.predict(x_train)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step


array([[2.88473586e-07, 1.81003520e-06, 2.92507815e-04, ...,
        5.27836019e-05, 2.29060788e-06, 6.13529701e-05],
       [9.99809921e-01, 2.94705899e-07, 1.34185699e-04, ...,
        5.93037839e-06, 2.83394957e-06, 1.77667589e-05],
       [4.50853840e-05, 2.20721282e-04, 2.07138080e-02, ...,
        2.19434383e-03, 3.27557354e-04, 1.14476383e-02],
       ...,
       [7.88127181e-08, 4.27814740e-07, 4.87575802e-09, ...,
        2.17441652e-07, 4.04835700e-05, 5.32558151e-05],
       [1.51911157e-03, 1.39023332e-05, 1.12858601e-03, ...,
        4.94260865e-04, 1.51889935e-05, 2.29225407e-05],
       [7.02550076e-03, 1.92115967e-05, 2.44926591e-03, ...,
        2.04418713e-04, 9.85816717e-01, 3.99196148e-03]],
      shape=(60000, 10), dtype=float32)

In [21]:
model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9676 - loss: 0.1066


[0.10656306147575378, 0.9675999879837036]

In [22]:
keras_model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9676 - loss: 0.1066


[0.10656306147575378, 0.9675999879837036]